config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :bookings
  resources :payment_methods
  resources :transactions
  resources :flights, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
end

app/models/flight.rb
class Flight < ApplicationRecord
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
require 'Spreedly'
require 'json'
require 'net/http'

class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @flight = Flight.find(params[:format])
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    spreedly = Spreedly.new
    
    payment_method = spreedly.create_payment_method(params)

    if payment_method.kind_of? Net::HTTPSuccess
      pm_parsed = JSON.parse(payment_method.body)
      pm_token = pm_parsed['transaction']['payment_method']['token']
    else
      # Bad payment method
      redirect_to '/flights', flash: { error: payment_method.body }
    end

    if(params[:pmd])
      # PMD 
      # - Get the receiver token. Create one if it doesn't exist.
      # - Create a payment method, get payment method token
      # - Use payment method token to process a purchase transaction
      receiver_token = spreedly.get_receiver_token
      # Save the payment method if user specified
      transaction = spreedly.payment_method_distribution(receiver_token, pm_token, params[:amount])
    else
      # Execute simple purchase transaction
      transaction = spreedly.create_purchase_transaction(params)
    end

    if(params[:store])
      PaymentMethod.create([
        {
          spreedly_payment_token: pm_token,
          primary_account_number: params[:credit_card],
          first_name: params[:first_name],
          last_name: params[:last_name],
          expiration_month: params[:expiration_month],
          expiration_year: params[:expiration_year],
        }
      ])
    end
      
    if transaction.kind_of? Net::HTTPSuccess 
      Transaction.create(
        { spreedly_transaction: transaction.body }
      )
    end
    
    redirect_to '/flights'
    # return transaction
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.fetch(:booking, {})
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
    @flight = Flight.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.fetch(:flight, {})
    end
end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  before_action :set_payment_method, only: [:show, :edit, :update, :destroy]

  # GET /payment_methods
  # GET /payment_methods.json
  def index
    @payment_methods = PaymentMethod.all
  end

  # GET /payment_methods/1
  # GET /payment_methods/1.json
  def show
  end

  # GET /payment_methods/new
  def new
    @payment_method = PaymentMethod.new
  end

  # GET /payment_methods/1/edit
  def edit
  end

  # POST /payment_methods
  # POST /payment_methods.json
  def create
    @payment_method = PaymentMethod.new(payment_method_params)

    respond_to do |format|
      if @payment_method.save
        format.html { redirect_to @payment_method, notice: 'Payment method was successfully created.' }
        format.json { render :show, status: :created, location: @payment_method }
      else
        format.html { render :new }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_methods/1
  # PATCH/PUT /payment_methods/1.json
  def update
    respond_to do |format|
      if @payment_method.update(payment_method_params)
        format.html { redirect_to @payment_method, notice: 'Payment method was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_method }
      else
        format.html { render :edit }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_methods/1
  # DELETE /payment_methods/1.json
  def destroy
    @payment_method.destroy
    respond_to do |format|
      format.html { redirect_to payment_methods_url, notice: 'Payment method was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_method
      @payment_method = PaymentMethod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_method_params
      params.fetch(:payment_method, {})
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.fetch(:transaction, {})
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def format_amount(amount)
        if amount
            ActiveSupport::NumberHelper.number_to_currency(
                amount/100.0
            )
        else
            "0.00"
        end
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/payment_methods_helper.rb
module PaymentMethodsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>Book Flight</h1>

<div class="booking">
    <div class="flight-details">
        <%= @flight.flight_no %>
        <%= @flight.departure %>
        <%= @flight.arrival %>
        <%= format_amount(@flight.price) %>
    </div>

    <div class="booking-form">
        <%= form_with(url: "/bookings", method: "post") do %>
            <%= label_tag(:credit_card, "Credit Card:") %>
            <%= text_field_tag(:credit_card) %>

            <%= label_tag(:first_name, "First Name:") %>
            <%= text_field_tag(:first_name) %>

            <%= label_tag(:last_name, "Last Name:") %>
            <%= text_field_tag(:last_name) %>

            <%= label_tag(:expiration_date, "Expiration Date:") %>
            Month: <%= text_field_tag(:expiration_month) %>
            Year: <%= text_field_tag(:expiration_year) %>

            <%= label_tag(:security_code, "Security Code:") %>
            <%= text_field_tag(:security_code) %>

            <%= label_tag(:store, "Save") %>
            <%= check_box_tag(:store) %><br>

            <%= label_tag(:pmd, "Book Through Expedia") %>
            <%= check_box_tag(:pmd) %><br>

            <%= hidden_field_tag(:amount, @flight.price) %>
            <%= hidden_field_tag(:id, @flight.id) %>

            <%= submit_tag("Book Flight") %>
        <% end%>
    </div>
</div>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/flights/_form.html.erb
<%= form_with(model: flight, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
        <% flight.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flights</h1>

<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><b>Flight Number</td>
      <td><b>Origin</td>
      <td><b>Destination</td>
      <td><b>Departure</td>
      <td><b>Arrival</td>
      <td><b>Price</td>
    <tr>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.flight_no %></td>
        <td><%= flight.origin %></td>
        <td><%= flight.destination %></td>
        <td><%= flight.departure %></td>
        <td><%= flight.arrival %></td>
        <td><%= format_amount(flight.price) %></td>
        <td><%= link_to 'Select', flight %></td>
        # <td><%= link_to 'Book Now', new_booking_path(flight.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<h1>
    <%= @flight.flight_no %>
    <%= @flight.origin %> flight to
    <%= @flight.destination %>
</h1>

<div>
    <div class="flight_details">
        <p> 
            Flight from <%= @flight.origin %>
            departs at <%= @flight.departure %>
            and arrives at <%= @flight.arrival %>
        </p>
        <%= link_to 'Book Flight', new_booking_path(@flight.id) %>
    </div>
</div>

<%= link_to 'Back', flights_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpreedlyAirlines</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= transaction.spreedly_transaction %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>@transaction</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>

app/views/welcome/index.html.erb
<h1>Spreedly Airlines!</h1>
<p><%= link_to 'Flights', "/flights" %></p>
<p><%= link_to 'Transactions', "/transactions" %></p>